{
 "title": "Wells",
 "time": { "from": "2007-12-31T23:00:00.000Z", "to": "2016-12-31T23:00:00.000Z" },
 "panels": [
  {
   "title": "Volumetric Data for Produced Oil, Water & Injected Water",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "m3" } },
   "targets": [
    {
     "rawSql": "SELECT time, \"Water Produced\", \"Oil Produced\", \"Water Injected\"\nFROM (\n  SELECT to_timestamp(productiontime, 'YYYY-MM-DD hh24:mi:ss') AS time,\n  borewatvol as \"Water Produced\",\n  boreoilvol as \"Oil Produced\",\n  borewivol as \"Water Injected\"\n  FROM production_data\n) subq\nWHERE $__timeFilter(time)\nORDER BY time"
    }
   ]
  },
  {
   "title": "Volumetric Data for Produced Gas",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "m3" } },
   "targets": [
    {
     "rawSql": "SELECT time, \"Gas Volume\"\nFROM (\n  SELECT to_timestamp(productiontime, 'YYYY-MM-DD hh24:mi:ss') AS time,\n  boregasvol \"Gas Volume\"\n  FROM production_data\n) subq\nWHERE $__timeFilter(time)\nORDER BY time"
    }
   ]
  },
  {
   "title": "Wells",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT well_legal_name as \"Well\",\nwellhead_depth as \"Well Depth\",\nwater_depth as \"Water Depth\"\nFROM wells_data\n"
    }
   ]
  },
  {
   "title": "Wells Geolocation",
   "type": "geomap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT well_legal_name as \"Well\",\ngeo_latitude as latitude,\ngeo_longitude as longitude\nFROM wells_data\n"
    }
   ]
  },
  {
   "title": "Wellbores",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT wellbore_name as \"Wellbore Name\",\nwell_legal_name as \"Well Legal Name\",\nko_md as \"Measured Depth\"\nFROM wellbores_data\n"
    }
   ]
  },
  {
   "title": "Wells Positions",
   "type": "geomap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "rawSql": "SELECT well_legal_name as \"Well\",\ngeo_latitude as latitude,\ngeo_longitude as longitude\nFROM wells_data\n"
    }
   ]
  }
 ]
}